export const POST_PROTEST_ERROR = 'POST_PROTEST_ERROR'
export const POST_PROTEST_SUCCESS = 'POST_SUCCESS_PROTEST'

export const GET_PROTEST_SUCCESS = 'GET_PROTEST_SUCCESS'
export const GET_PROTEST_ERROR = 'GET_PROTEST_ERROR'
